### ISSUE TITLE
AdyenCheckout onSubmit Method called many times

### ISSUE THREAD

**Issue by faizantariq2** [Adyen/adyen-react-native#44]
**Describe the bug**
Please run the sample project

**To Reproduce**
1. Created a functional component inside this component  place a component of AdyenCheckout in return statement.
<AdyenCheckout
  config={configuration}
  paymentMethods={paymentMethods}
  onSubmit={didSubmit}
  onProvide={didProvide}
  onFail={didFail}
  onComplete={didComplete} >
    <MyChekoutView/>
</AdyenCheckout>

2. So, when i navigation first time in this functional component it's onSubmit method called once and after all the payment process done or even in case of cancel first time it's working fine. Then again i navigate again to this functional component and go for payment it's onSubmit method called twice and so on.

3. i think the problem is that in AdyenCheckout component it's attach the listner multiple times when it navigate into that functional component multiple time. you need to remove the listner in AdyenCheckout before attaching a new one.

**Expected behavior**
it's should be called only one time.

Producible on Devices:
Platform: iOS & Android both
Device: Any
OS: Any
Version: 1.0.0 [BETA.5]

**Comment by descorp** [comment]
Hey @faizantariq2 

Thanks for reaching out!

How do you initate a payment?
If yo are using [start('XXX')](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/PaymentMethodsView.js#L43) function from `AdyenCheckoutContext` the listeners [removed](https://github.com/Adyen/adyen-react-native/blob/develop/src/AdyenCheckoutContext.js#L42-L47) every time new payment started or canceled.

Could be that you are generating new instances of `AdyenCheckoutContext`, so that every time you generate new listeners?

**Comment by descorp** [comment]
Hey @faizantariq2 thanks for sharing!
Could you provide more context?
I would like to understand how do you create `AdyenCheckout`

**Comment by faizantariq2** [comment]
Hi @descorp ,

MyChekoutView page is just a functional component where i start the payment method on button press.
with the help of this hook.

`const { start } = useAdyenCheckout();`

and onPress
```
onPress={()=>{
start('paypal);
}}
```

**Comment by descorp** [comment]
I mean `<AdyenCheckout>` and the component around it. I am trying to reproduce this bug, so I need to mimic your setup.

**Comment by faizantariq2** [comment]
```
const PaymentsScreen = ({ navigation, route }) => {
     const configuration = {
   //here just directly passing the desired configurations
  };
  const [paymentMethods, setPaymentMethods] = useState<Object>(undefined);
  useEffect(() => {
    getPaymentMethods();
  }, []);

  const getPaymentMethods = async () => {
  
    const paymentMethods = await fetchPaymentMethods(paymentsParam); //here you can say fetching the payment methods
  
    setPaymentMethods(paymentMethods);
  };

  const didSubmitCallback = (
    val: { paymentMethod: any; storePaymentMethod: any; returnUrl: string },
    nativeComponent: any,
  ) => {
  fetchPayments(params)
      .then((result: { action: any }) => {
       if (result.action) {
          nativeComponent.handle(result.action);
        } else {
         nativeComponent.hide(false, {
      message: ‘success’,
    });

        }
       })
      .catch((error: any) => {  nativeComponent.hide(false, {
      message: error.message || 'Unknown error',
    }); });

  };

  const didProvideCallback = (val: any, nativeComponent: any) => {     .fetchPaymentDetails(val)
      .then((result: any) =>{
 nativeComponent.hide(false, {
      message: ‘success’,
    });
})
      .catch((error: any) => {  nativeComponent.hide(false, {
      message: error.message || 'Unknown error',
    }); });

    };

  const didCompleteCallback = (val: any, nativeComponent: any) => {
    nativeComponent.hide(true, { message: 'Completed' });
  };

  const didFailCallback = (error: any, nativeComponent: any) => {  nativeComponent.hide(false, {
      message: error.message || 'Unknown error',
    });

      };

 
Const onPressCallBack = (start) =>{ 	start(‘scheme’); }


  return (
    <AdyenCheckout
      config={configuration}
      paymentMethods={paymentMethods}
      onSubmit={didSubmitCallback}
      onProvide={didProvideCallback}
      onFail={didFailCallback}
      onComplete={didCompleteCallback}>
      <CheckoutScreen onPressCallBack={onPressCallBack} />
    </AdyenCheckout>
  );
};

export default PaymentsScreen;

```

CheckOut.

```

const CheckoutScreen: FC<ICheckoutScreenProps> = ({
  navigation,
  route,
onPressCallBack
}) => {
  const { start } = useAdyenCheckout();
  

  return (
  <MyButton  onPress={()=>{ onPressCallBack(start); }} />
  );
};

export default CheckoutScreen;


```

**Comment by descorp** [comment]
Thanks @faizantariq2 

I'll play with it in attempt to reproduce it

**Comment by descorp** [comment]
@faizantariq2 

BTW, is this a problem for both iOS and Android?

**Comment by faizantariq2** [comment]
Yes it's produceable on both IOS and Android.

**Comment by descorp** [comment]
This is good! At least it means the problem is on JS side.

Thanks to @kadikraman on this #46 ticket, I have spotted odd behaviour on Android `AdyenInstant` - the `ActionHandler` on Android is "stacking" up listeners. Now I know those things are unrelated..

**Comment by descorp** [comment]
Good news! I was able to reproduce this issue and seems like this PR #47 will fix it

**Comment by faizantariq1** [comment]
that's great.

**Comment by iranaahsanali** [comment]
@descorp Can you please share the timeline, for when this issue will be fixed? It's a big blocker for me.

**Comment by descorp** [comment]
Hey @iranaahsanali 

The issue is already fixed, hopefully the fix will be released end of this or begging of the next week.

**Comment by kadikraman** [comment]
Hi @descorp - we're running into this issue as well.

You say that this is already fixed - are you referring to [this](https://github.com/Adyen/adyen-react-native/commit/5d6a7d04bcb679bf086762c41ed75c46362300be) commit? We've just tried it with that change, and we can still reproduce the issue. Also I don't think it's a JavaScript bug as it *only* happens on Android. For this reason it is likely a bug either in some android-specific code or in the android SDK.

To reproduce:
1. start payment on Android
2. cancel payment with the "cancel and go back to XX"
3. -> `handleDidProvide` gets called once with a cancel result
4. start payment again (in the same session)
5. -> `handleDidProvide` gets called twice with a cancel result
6. start payment again (in the same session)
7. -> `handleDidProvide` gets called three times with a cancel result
8. etc

The other (for us more serious) issue we're having that is also Android specific is:
1. start payment on Android
2. cancel payment with the "cancel and go back to XX"
3. -> `handleDidProvide` gets called once with a cancel result
4. start payment again (in the same session)
5. -> `handleDidProvide` gets called _immediately_ with a cancel result, without doing anything in the webview. This means that it is not possible to complete a payment once you've cancelled once because the cancel flow is triggered immediately.

Please let me know if there's any additional information I can provide and if I should create a separate issue for this.

**Comment by descorp** [comment]
Hey @faizantariq1  @kadikraman 

This bug should be fixed in [1.0.0-beta6](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.6)
Could you verify?

**Comment by iranaahsanali** [comment]
This issue is fixed, but it created a new issue. 
https://github.com/Adyen/adyen-react-native/issues/61

**Comment by descorp** [comment]
I'll close this issue, since we figured out reason for #61
